### ISSUE TITLE
python3.7 wheels?

### ISSUE THREAD

**Issue by ngoldbaum** [MacPython/astropy-wheels#21]
Multibuild supports python3.7 wheels now. I got that set up for yt if you want to look at something to compare with: https://github.com/yt-project/yt-wheels/pull/3

I have a couple projects that depend on astropy so it's nice to have wheels uploaded to pypi so those builds run faster.

**Comment by bsipocz** [comment]
Thanks @ngoldbaum! We still haven't ironed out all the python3.7 dependency issues, but if that's done, I foresee that I'll have to do some releases.

**Comment by bsipocz** [comment]
We have 3.7 wheels for a while now, we just forgot to close this issue.
