### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by bsipocz** [MacPython/astropy-wheels#68]
as it's not being used any more

**Comment by mattip** [comment]
@bsipocz do we need any other maintainers to chime in or should I archive it?

**Comment by bsipocz** [comment]
I don't think anyone else needs to be chimed in and this can be archived now. But if you want to wait `astrofrog` and `saimn` are the ones to be pinged.

**Comment by astrofrog** [comment]
I agree this can be archived!

**Comment by mattip** [comment]
OK, I will archive it.
